/**
 * 配置项定义（settings 表元数据）
 */
export const CONFIG_DEFINITIONS: Record<string, { label: string; description?: string }> = {
  emby_base_url: { label: 'Emby 地址', description: 'Emby 服务器 URL' },
  emby_api_key: { label: 'API 密钥', description: 'Emby API Key' },
  emby_proxy_enabled: { label: '启用反代', description: '是否启用 Emby 反代服务' },
  emby_proxy_port: { label: '反代端口', description: 'Emby 反代监听端口' },
  pan115_cookie: { label: '云盘 CK', description: '115 云盘 Cookie' },
  pan115_save_dir: { label: '云盘保存目录', description: '115 保存目录' },
  pan115_media_dir: { label: '云盘媒体库目录', description: '115 媒体库目录' },
  pan115_app_id: { label: '115 开放平台 AppID', description: '用于直链服务' },
  pan115_open_token: { label: '115 开放平台 Token', description: 'access_token' },
  pan115_refresh_token: { label: '115 开放平台 RefreshToken', description: 'refresh_token' },
  pan115_token_expire: { label: '115 Token 过期时间', description: 'access_token 过期时间戳' },
  tmdb_api_url: { label: 'TMDB API 地址', description: 'TMDB API 代理地址' },
  tmdb_api_key: { label: 'TMDB API 密钥', description: 'TMDB API Key' },
  rename_movie_template: { label: '电影命名模板', description: '电影重命名模板' },
  rename_tv_template: { label: '电视剧命名模板', description: '电视剧重命名模板' },
  classification_strategy: { label: '分类策略', description: '媒体分类策略配置' },
  custom_release_groups: { label: '自定义发布组', description: '补充发布组列表' },
  auto_organize_enabled: { label: '自动整理开关', description: '是否启用自动整理' },
  auto_organize_action: { label: '自动整理方式', description: 'move 或 copy' },
  auto_organize_cron: { label: '自动整理时间', description: 'Cron 表达式' },
  telegram_api_id: { label: 'Telegram API ID', description: '来自 my.telegram.org' },
  telegram_api_hash: { label: 'Telegram API Hash', description: '来自 my.telegram.org' },
  telegram_phone: { label: 'Telegram 手机号', description: '含国际区号' },
  telegram_session_string: { label: 'Telegram Session', description: '登录会话字符串' },
  telegram_mode: { label: 'Telegram 模式（已弃用）', description: '兼容旧数据' },
  telegram_bot_token: { label: 'Telegram Bot Token', description: '来自 @BotFather' },
  telegram_proxy_enabled: { label: 'Telegram 代理开关', description: '是否启用代理' },
  telegram_proxy_url: { label: 'Telegram 代理地址', description: 'socks5/http 代理 URL' },
  telegram_admin_ids: { label: 'Telegram 管理员 ID', description: '逗号分隔' },
  telegram_whitelist_chats: { label: 'Telegram 白名单会话', description: '逗号分隔' },
  telegram_notify_chat: { label: 'Telegram 通知会话', description: '通知目标 chat id' },
  wechat_token: { label: '微信 Token', description: '微信机器人 token' },
  wechat_bot_id: { label: '微信 Bot ID', description: '机器人 ID' },
  wechat_user_id: { label: '微信用户 ID', description: '登录用户 ID' },
  wechat_notify_user_id: { label: '微信通知用户', description: '通知目标用户' },
  wechat_sync_buf: { label: '微信同步缓冲', description: '内部同步状态' },
  wechat_sdk_credentials: { label: '微信 SDK 凭证', description: '内部凭证' },
  wechat_sdk_cursor: { label: '微信 SDK 游标', description: '内部游标' },
  wechat_sdk_context_tokens: { label: '微信上下文 Token', description: '内部上下文' },
  wechat_sdk_typing_tickets: { label: '微信输入态票据', description: '内部票据' },
  strm_server_url: { label: 'STRM 服务地址', description: 'STRM 播放服务 URL' },
  strm_output_path: { label: 'STRM 输出路径', description: '授权目录下的输出路径' },
  task_checkin_enabled: { label: '115 签到开关', description: '定时签到' },
  task_checkin_schedule: { label: '115 签到计划', description: 'Cron' },
  task_checkin_last_run: { label: '115 签到上次运行', description: '时间戳/文本' },
  task_clean_trash_enabled: { label: '清空回收站开关', description: '定时清理' },
  task_clean_trash_schedule: { label: '清空回收站计划', description: 'Cron' },
  task_clean_trash_last_run: { label: '清空回收站上次运行', description: '时间戳/文本' },
  fnos_cookie: { label: '飞牛 Cookie', description: '飞牛签到 Cookie' },
  task_fnos_sign_enabled: { label: '飞牛签到开关', description: '定时签到' },
  task_fnos_sign_schedule: { label: '飞牛签到计划', description: 'Cron' },
  task_fnos_sign_last_run: { label: '飞牛签到上次运行', description: '时间戳/文本' },
  glados_cookie: { label: 'GLaDOS Cookie', description: 'GLaDOS 签到 Cookie' },
  task_glados_sign_enabled: { label: 'GLaDOS 签到开关', description: '定时签到' },
  task_glados_sign_schedule: { label: 'GLaDOS 签到计划', description: 'Cron' },
  task_glados_sign_last_run: { label: 'GLaDOS 签到上次运行', description: '时间戳/文本' },
  hdhive_cookie: { label: 'HDHive Cookie', description: 'HDHive 签到 Cookie' },
  hdhive_base_url: { label: 'HDHive 地址', description: '站点 URL' },
  task_hdhive_sign_enabled: { label: 'HDHive 签到开关', description: '定时签到' },
  task_hdhive_sign_schedule: { label: 'HDHive 签到计划', description: 'Cron' },
  task_hdhive_sign_last_run: { label: 'HDHive 签到上次运行', description: '时间戳/文本' },
  task_media_info_enabled: { label: '媒体信息任务开关', description: '定时提取' },
  task_media_info_schedule: { label: '媒体信息任务计划', description: 'Cron' },
  task_media_info_last_run: { label: '媒体信息上次运行', description: '时间戳/文本' },
  task_media_info_library_id: { label: '媒体信息媒体库', description: '目标库 ID' },
  task_media_info_concurrency: { label: '媒体信息并发', description: '并发数' },
  task_media_info_follow_enabled: { label: '媒体信息追更开关', description: '新入库追更' },
  task_media_info_follow_last_run: { label: '媒体信息追更上次运行', description: '时间戳/文本' },
  ai_recognize_enabled: { label: 'AI 识别开关', description: '是否启用 AI 辅助识别' },
  ai_api_key: { label: 'AI API 密钥', description: '模型服务 Key' },
  ai_api_url: { label: 'AI API 地址', description: '模型服务 URL' },
  ai_model: { label: 'AI 模型', description: '模型名称' },
  path_mapping: { label: '路径映射', description: 'Emby 与本地路径映射，JSON 数组' }
}
